using AspireApp.Web.Data;
using AspireApp.Web.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;

namespace AspireApp.Web.Services;

/// <summary>
/// Ensures the local auth table exists in persisted PostgreSQL stores and seeds missing dev accounts.
/// </summary>
public sealed class LocalAuthBootstrapper(
    UploadDbContext dbContext,
    IOptions<LocalAuthenticationOptions> options,
    TenantManagementService tenantManagementService)
{
    private const string NpgsqlProviderName = "Npgsql.EntityFrameworkCore.PostgreSQL";

    private readonly UploadDbContext _dbContext = dbContext;
    private readonly LocalAuthenticationOptions _options = options.Value;
    private readonly TenantManagementService _tenantManagementService = tenantManagementService;

    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (string.Equals(_dbContext.Database.ProviderName, NpgsqlProviderName, StringComparison.Ordinal))
        {
            await EnsureSchemaAsync(cancellationToken);
        }

        await SeedUsersAsync(cancellationToken);
        await BackfillLocalUserTenantsAsync(cancellationToken);
    }

    private async Task EnsureSchemaAsync(CancellationToken cancellationToken)
    {
        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS local_auth_users (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username character varying(100) NOT NULL,
                normalized_username character varying(100) NOT NULL,
                email character varying(256) NOT NULL,
                normalized_email character varying(256) NOT NULL,
                display_name character varying(200) NOT NULL,
                password_hash text NOT NULL,
                default_tenant_id character varying(100) NOT NULL,
                is_active boolean NOT NULL DEFAULT TRUE,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_at timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_local_auth_users_normalized_username
            ON local_auth_users (normalized_username);
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_local_auth_users_normalized_email
            ON local_auth_users (normalized_email);
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS idx_local_auth_users_is_active
            ON local_auth_users (is_active);
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS idx_local_auth_users_default_tenant
            ON local_auth_users (default_tenant_id);
            """,
            cancellationToken);
    }

    private async Task SeedUsersAsync(CancellationToken cancellationToken)
    {
        if (_options.SeedUsers.Count == 0)
        {
            return;
        }

        ValidateSeedUsers();

        var existingIdentifiers = await _dbContext.LocalAuthUsers
            .AsNoTracking()
            .Select(user => new { user.NormalizedUsername, user.NormalizedEmail })
            .ToListAsync(cancellationToken);

        var knownUsernames = new HashSet<string>(
            existingIdentifiers.Select(value => value.NormalizedUsername),
            StringComparer.OrdinalIgnoreCase);
        var knownEmails = new HashSet<string>(
            existingIdentifiers.Select(value => value.NormalizedEmail),
            StringComparer.OrdinalIgnoreCase);

        foreach (var seedUser in _options.SeedUsers)
        {
            var normalizedUsername = LocalAuthValueNormalizer.Normalize(seedUser.Username);
            var normalizedEmail = LocalAuthValueNormalizer.Normalize(seedUser.Email);

            if (knownUsernames.Contains(normalizedUsername) || knownEmails.Contains(normalizedEmail))
            {
                continue;
            }

            var timestamp = DateTime.UtcNow;
            _dbContext.LocalAuthUsers.Add(new LocalAuthUser
            {
                Username = LocalAuthValueNormalizer.Clean(seedUser.Username),
                NormalizedUsername = normalizedUsername,
                Email = LocalAuthValueNormalizer.Clean(seedUser.Email),
                NormalizedEmail = normalizedEmail,
                DisplayName = LocalAuthValueNormalizer.Clean(seedUser.DisplayName),
                PasswordHash = seedUser.PasswordHash.Trim(),
                DefaultTenantId = string.Empty,
                IsActive = true,
                CreatedAt = timestamp,
                UpdatedAt = timestamp
            });

            knownUsernames.Add(normalizedUsername);
            knownEmails.Add(normalizedEmail);
        }

        await _dbContext.SaveChangesAsync(cancellationToken);
    }

    private async Task BackfillLocalUserTenantsAsync(CancellationToken cancellationToken)
    {
        var users = await _dbContext.LocalAuthUsers
            .Where(user => user.IsActive)
            .ToListAsync(cancellationToken);

        if (users.Count == 0)
        {
            return;
        }

        var hasChanges = false;

        foreach (var user in users)
        {
            var tenantSnapshot = await _tenantManagementService.EnsureTenantAccessAsync(
                new TenantUserDescriptor($"local-{user.Id}", user.DisplayName, user.Email),
                cancellationToken);

            if (string.Equals(user.DefaultTenantId, tenantSnapshot.DefaultTenantId, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            user.DefaultTenantId = tenantSnapshot.DefaultTenantId;
            user.UpdatedAt = DateTime.UtcNow;
            hasChanges = true;
        }

        if (hasChanges)
        {
            await _dbContext.SaveChangesAsync(cancellationToken);
        }
    }

    private void ValidateSeedUsers()
    {
        var knownIdentifiers = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var seedUser in _options.SeedUsers)
        {
            if (string.IsNullOrWhiteSpace(seedUser.Username))
            {
                throw new InvalidOperationException("Authentication:Local:SeedUsers entries require a Username.");
            }

            if (string.IsNullOrWhiteSpace(seedUser.Email))
            {
                throw new InvalidOperationException("Authentication:Local:SeedUsers entries require an Email.");
            }

            if (string.IsNullOrWhiteSpace(seedUser.DisplayName))
            {
                throw new InvalidOperationException("Authentication:Local:SeedUsers entries require a DisplayName.");
            }

            if (string.IsNullOrWhiteSpace(seedUser.PasswordHash))
            {
                throw new InvalidOperationException("Authentication:Local:SeedUsers entries require a precomputed PasswordHash.");
            }

            var normalizedUsername = $"username:{LocalAuthValueNormalizer.Normalize(seedUser.Username)}";
            var normalizedEmail = $"email:{LocalAuthValueNormalizer.Normalize(seedUser.Email)}";

            if (!knownIdentifiers.Add(normalizedUsername) || !knownIdentifiers.Add(normalizedEmail))
            {
                throw new InvalidOperationException("Authentication:Local:SeedUsers contains duplicate usernames or emails.");
            }
        }
    }
}
