using AspireApp.Web.Shared;
using Microsoft.EntityFrameworkCore;

namespace AspireApp.Web.Services;

/// <summary>
/// Ensures tenant tables exist in persisted PostgreSQL stores.
/// </summary>
public sealed class TenantStoreBootstrapper(UploadDbContext dbContext)
{
    private const string NpgsqlProviderName = "Npgsql.EntityFrameworkCore.PostgreSQL";

    private readonly UploadDbContext _dbContext = dbContext;

    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();

        if (string.Equals(_dbContext.Database.ProviderName, NpgsqlProviderName, StringComparison.Ordinal))
        {
            await EnsureSchemaAsync(cancellationToken);
        }
    }

    private async Task EnsureSchemaAsync(CancellationToken cancellationToken)
    {
        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS tenants (
                id character varying(100) PRIMARY KEY,
                name character varying(200) NOT NULL,
                owner_user_id character varying(200) NOT NULL,
                is_protected boolean NOT NULL DEFAULT FALSE,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                updated_at timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS tenant_memberships (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                tenant_id character varying(100) NOT NULL,
                user_id character varying(200) NOT NULL,
                is_default boolean NOT NULL DEFAULT FALSE,
                created_at timestamp with time zone NOT NULL DEFAULT NOW(),
                CONSTRAINT fk_tenant_memberships_tenant
                    FOREIGN KEY (tenant_id)
                    REFERENCES tenants(id)
                    ON DELETE CASCADE
                    ON UPDATE CASCADE
            );
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS ux_tenant_memberships_tenant_user
            ON tenant_memberships (tenant_id, user_id);
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS idx_tenant_memberships_user
            ON tenant_memberships (user_id);
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS idx_tenant_memberships_tenant
            ON tenant_memberships (tenant_id);
            """,
            cancellationToken);

        await _dbContext.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS idx_tenants_owner_user
            ON tenants (owner_user_id);
            """,
            cancellationToken);
    }
}
